version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./store:/store

  bossqu-ai:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bossqu-ai
    environment:
      - CHROMA_PERSIST_DIRECTORY=/store
      - PORT=7788
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    ports:
      - "7788:7788"
    volumes:
      - ./store:/store
